### ISSUE TITLE
Glibc error when installing on linux

### ISSUE THREAD

**Issue by moble** [JuliaLang/juliaup#359] opened 2022-08-02 16:13 UTC
Trying to install on a cluster, I get this error:
```bash
> curl -fsSL https://install.julialang.org | sh

info: downloading installer
/tmp/tmp.sFMh2SHBpA/juliainstaller: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/tmp.sFMh2SHBpA/juliainstaller)
```

I acknowledge that I don't have 2.18; if I'm not mistaken, my cluster has glibc 2.17:

```bash
> ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

But according to this comment, and the link it contains, it looks like 2.12.2 should work:

> What's the oldest glibc Julia supports otherwise (and what julia up supports)?

For Julia, it depends on the architecture: https://github.com/JuliaPackaging/Yggdrasil/blob/3aa25f9eb060cfc435583f280e675396d089055e/0_RootFS/gcc_common.jl#L245

_Originally posted by @DilumAluthge in https://github.com/JuliaLang/juliaup/issues/350#issuecomment-1201972558_

It's an x86_64 Linux cluster:

```bash
> uname -a
Linux wheeler 3.10.0-327.36.3.el7.x86_64 #1 SMP Thu Oct 20 04:56:07 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Is this not expected to work?

**Comment by simeonschaub** [comment] 2022-08-02 19:31
Looks like a duplicate of #321

**Closed by simeonschaub** 2022-08-02 19:31 UTC
