### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by BeeGass** [JuliaLang/juliaup#377] opened 2022-08-12 16:44 UTC
My system info:
```bash
Software:
    System Software Overview:
      System Version: macOS 12.5 (21G72)
      Kernel Version: Darwin 21.6.0
      Boot Volume: Macintosh HD

Hardware:
    Hardware Overview:
      Model Name: MacBook Pro
      Chip: Apple M1 Pro
      Total Number of Cores: 8 (6 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 7459.141.1
      OS Loader Version: 7459.141.1
```

To recreate the issue:

installed through curl
```bash
curl -fsSL https://install.julialang.org | sh
```

reload my session
```bash
. ~/.zshrc
```

attempt to start julia and receive error output
```bash
julia
> Error: The Julia launcher failed to start Julia.
>
> Caused by:
>     Bad CPU type in executable (os error 86)
```

I havent seen any issues regarding this, was hoping to get some help.

**Comment by davidanthoff** [comment] 2022-08-12 16:54
I think you are running into https://github.com/JuliaLang/juliaup/issues/239. See the discussion there. I'm closing for now, but please reopen if this was caused by something else.

**Closed by davidanthoff** 2022-08-12 16:54 UTC

**Comment by BeeGass** [comment] 2022-08-12 17:54
You are completely right. That solved the issue. Thank you
