### ISSUE TITLE
Failure with readonly .bashrc in linux

### ISSUE THREAD

**Issue by DrChainsaw** [JuliaLang/juliaup#640] opened 2023-05-12 07:45 UTC
It might also be a problem that it ignores the customization option to not modify the config files or else I don't see why it should fail in this case:

```
✔ Do you want to install with these default configuration choices? · Customize installation

✔ Enter the folder where you want to install Juliaup · /home/<redacted>/.juliaup
✔ Do you want to add the Julia binaries to your PATH by manipulating various shell startup scripts? · no
✔ Do you want to add channel specific symlinks? · no
✔ Enter minutes between check for new version at julia startup, use 0 to disable · 1440
✔ Enter minutes between check for new version by a background task, use 0 to disable · 0
Juliaup will be installed into the Juliaup home directory, located at:

  /home/<redacted>/.juliaup

The julia, juliaup and other commands will be added to
Juliaup's bin directory, located at:

  /home/<redacted>/.juliaup/bin

Julia will look for a new version of Juliaup itself every 1440 minutes when you start julia.

✔ Do you want to install with these custom configuration choices? · Proceed with installation
Now installing Juliaup
Well, this is embarrassing.

Juliainstaller had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-4a2e0dbe-147a-432c-8c5f-2e802e7c9321.toml". Submit an issue or email with the subject of "Juliainstaller Crash Report" and include the report as an attachment.

- Homepage: https://github.com/JuliaLang/juliaup

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!

$ cat /tmp/report-4a2e0dbe-147a-432c-8c5f-2e802e7c9321.toml
name = 'Juliainstaller'
operating_system = 'unix:Unknown'
crate_version = '1.8.16'
explanation = '''
Panic occurred in file 'src/operations.rs' at line 758
'''
cause = '''
called `Result::unwrap()` on an `Err` value: Failed to open file: /home/<redacted>/.bashrc

Caused by:
    Permission denied (os error 13)'''
method = 'Panic'
backtrace = '''

   0: 0x7f9ac7b50891 - juliainstaller::main::h65fb13bb33c5f160
   1: 0x7f9ac7b33b53 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6fe083bbd940dc5e
   2: 0x7f9ac7b57c41 - main'''

$ ls -l .bashrc
-r--r--r-- 1 <redacted> .bashrc
```

**Comment by jjvliu** [comment] 2023-05-15 18:08
Duplicate of #624. Seems like this is pretty common for folks (myself included).

**Comment by davidanthoff** [comment] 2023-06-27 19:04
Closing because of dup.

**Closed** 2023-06-27 19:04 UTC
