### ISSUE TITLE
Installation attempt crash report

### ISSUE THREAD

**Issue by suzycheung** [JuliaLang/juliaup#985] opened 2024-07-08 17:41 UTC
I encountered the following error when attempting to install Julia with the command `curl -fsSL https://install.julialang.org | sh`

This is from the toml file:

```
"name" = "Juliainstaller"
"operating_system" = "Mac OS 14.5.0 [64-bit]"
"crate_version" = "1.14.9"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1021
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/suzy/.bash_profile.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x104583d94 - core::result::unwrap_failed::h8e3b933261dd7fec
   1: 0x104447990 - juliaup::command_config_modifypath::run_command_config_modifypath::hca63d35b576be3c9
   2: 0x10435758c - juliainstaller::main::hb0bee2b2a4d9e158
   3: 0x104343268 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2b1ac18042ef3658
   4: 0x10435bc4c - _main"""
```

**Comment by mortenpi** [comment] 2024-08-12 06:33
Duplicate of https://github.com/JuliaLang/juliaup/issues/920 I think.

**Closed** 2024-08-21 01:04 UTC
