### ISSUE TITLE
Issue installing Juliaup with curl command on Macbook Silicon (Apple M1 Chip)

### ISSUE THREAD

**Issue by unary-code** [JuliaLang/juliaup#663] opened 2023-06-25 20:31 UTC
I was not able to install juliaup using the curl command.
I remember that I was able to install juliaup with the "brew install juliaup" command, BUT the PySR README says that when you install juliaup through brew (a OS-specific software), that leads to some issues later when you try to use juliaup.
QUOTE (from the PySR README): "As of now, we strongly recommend to install Juliaup via the curl command above rather than through OS-specific software repositories (see below) as the Juliaup variants provided by the latter currently have some drawbacks"
In addition, when I used the Juliaup that I installed through brew, that gave me a error when I tried to use PySR package:
```
Compiling Julia backend...
(some outputted lines)
OSError: dlopen(/Users/[MYUSER]/.julia/juliaup/julia-1.9.1+0.aarch64.apple.darwin14/lib/libjulia.1.9.dylib, 0x000A): tried: '/Users/[MYUSER]/.julia/juliaup/julia-1.9.1+0.aarch64.apple.darwin14/lib/libjulia.1.9.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libjulia.1.9.dylib' (no such file), '/usr/lib/libjulia.1.9.dylib' (no such file)
```

Anyways, back to my main question: I was not able to install julia using the curl command.
When I did "curl -fsSL https://install.julialang.org | sh", I got this error:
```
Now installing Juliaup
Well, this is embarrassing.

Juliainstaller had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/var/folders/hk/7vbk1d0x74dcjw_wpf8mp38h0000gn/T/report-8251e3cd-43d3-4e07-b758-b1cd4982c7bb.toml". Submit an issue or email with the subject of "Juliainstaller Crash Report" and include the report as an attachment.

- Homepage: https://github.com/JuliaLang/juliaup

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
```

Here is my Crash report (the contents of "/var/folders/hk/7vbk1d0x74dcjw_wpf8mp38h0000gn/T/report-8251e3cd-43d3-4e07-b758-b1cd4982c7bb.toml"):
```
name = 'Juliainstaller'
operating_system = 'unix:OSX'
crate_version = '1.8.16'
explanation = '''
Panic occurred in file 'src/operations.rs' at line 749
'''
cause = '''
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/davidkatz/.bash_profile.

Caused by:
    Permission denied (os error 13)'''
method = 'Panic'
backtrace = '''

   0: 0x1008aca88 - juliaup::command_config_modifypath::run_command_config_modifypath::h0f87529dd7cef58e
   1: 0x1007f30a8 - juliainstaller::main::h6342f9beb07f076b
   2: 0x1007dc0d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::hda91fd22e5148544
   3: 0x1007f8b7c - _main'''
```

Thank you!

**Comment by davidanthoff** [comment] 2023-06-27 19:13
Couple of points:
1. From my end there is no drawback from installing via brew, that is as well supported as the curl command.
2. The error message from the PySR thing suggests an error in that package: somehow they are trying to load an aarch64 binary of Julia into a x64 process. I'm not familiar enough with that package to say why, but if you need a x64 Julia binary you can install that with `juliaup add release~x64` and then that should be loadable from a x64 process.
3. The error messages you got from the curl install are a duplicate of https://github.com/JuliaLang/juliaup/issues/624.

I'm going to close this issue for now because we are tracking the one bug elsewhere already.

**Closed by davidanthoff** 2023-06-27 19:13 UTC
