### ISSUE TITLE
[new feature] automatic select julia version from Manifest.toml file

### ISSUE THREAD

**Issue by lmiq** [JuliaLang/juliaup#617] opened 2023-04-20 14:00 UTC
It would be neat if juliaup could automatically install (if not installed yet) and use a Julia version corresponding to that of a Manifest of the current environment. 

Currently, if the julia version does not match the one used in the Manifest.toml file one gets a warning and, later, possibly a lot of errors.

Put simply, given a Manifest starting with:

```
julia_version = "1.8.2"
manifest_format = "2.0"
```

running `julia --project ./script.jl` would automatically use `Julia 1.8.X`.

**Comment by davidanthoff** [comment] 2023-04-20 17:26
Duplicate of https://github.com/JuliaLang/juliaup/issues/10 :)

**Closed by davidanthoff** 2023-04-20 17:26 UTC
