### ISSUE TITLE
Hard-coded?

### ISSUE THREAD

**Issue by uncomfyhalomacro** [JuliaLang/juliaup#284] opened 2022-04-10 03:13 UTC
Hello! 
I have a question regarding this https://github.com/JuliaLang/juliaup/blob/1c9132470740b10f17640cdea3dff623024a1a0f/build.rs#L21-L66. Is this intentionally hard-coded? 
Would it be better if we actually use the JSON from https://julialang-s3.julialang.org/bin/versions.json?

EDIT: I guess I have not read everything in the code base if it uses it.

**Comment by simeonschaub** [comment] 2022-04-10 04:32
Duplicate of https://github.com/JuliaLang/juliaup/issues/131

**Closed by simeonschaub** 2022-04-10 04:32 UTC
