### ISSUE TITLE
Trouble installing Julia 1.0.0–1.3

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/juliaup#374] opened 2022-08-10 13:41 UTC
1.0 fails to extract and other versions fail to download. version 1.4 "Just works"
```
x@X % juliaup add 1.0.0
Installing Julia 1.0.0+0.x64 (x64).
Error: Failed to download from url `https://julialang-s3.julialang.org/bin/mac/x64/1.0/julia-1.0.0-mac64.tar.gz`.

Caused by:
    https://julialang-s3.julialang.org/bin/mac/x64/1.0/julia-1.0.0-mac64.tar.gz: status code 404
x@X % juliaup add 1.0
Installing Julia 1.0.5+0.x64 (x64).
Error: Failed to extract downloaded file from url `https://julialang-s3.julialang.org/bin/mac/x64/1.0/julia-1.0.5-mac64.tar.gz`.

Caused by:
    0: failed to unpack `julia-1.0.5/LICENSE.md` into `/Users/x/.julia/juliaup/julia-1.0.5+0.x64/LICENSE.md`
    1: No such file or directory (os error 2)
x@X % juliaup add 1.1  
Installing Julia 1.1.1+0.x64 (x64).
Error: Failed to download from url `https://julialang-s3.julialang.org/bin/mac/x64/1.1/julia-1.1.1-mac64.tar.gz`.

Caused by:
    https://julialang-s3.julialang.org/bin/mac/x64/1.1/julia-1.1.1-mac64.tar.gz: status code 404
x@X % juliaup add 1.2
Installing Julia 1.2.0+0.x64 (x64).
Error: Failed to download from url `https://julialang-s3.julialang.org/bin/mac/x64/1.2/julia-1.2.0-mac64.tar.gz`.

Caused by:
    https://julialang-s3.julialang.org/bin/mac/x64/1.2/julia-1.2.0-mac64.tar.gz: status code 404
x@X % juliaup add 1.3
Installing Julia 1.3.1+0.x64 (x64).
Error: Failed to download from url `https://julialang-s3.julialang.org/bin/mac/x64/1.3/julia-1.3.1-mac64.tar.gz`.

Caused by:
    https://julialang-s3.julialang.org/bin/mac/x64/1.3/julia-1.3.1-mac64.tar.gz: status code 404
x@X % juliaup add 1.4
Installing Julia 1.4.2+0.x64 (x64).
x@X % julia +1.4                             
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.2 (2020-05-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> 
```

**Comment by davidanthoff** [comment] 2022-08-11 16:46
Duplicate of https://github.com/JuliaLang/juliaup/issues/184 and https://github.com/JuliaLang/juliaup/issues/183.

**Closed by davidanthoff** 2022-08-11 16:46 UTC

**Comment by LilithHafner** [comment] 2022-08-11 20:42
Thanks! sorry for the noise.
