### ISSUE TITLE
juliaup does not support PowerPC

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/juliaup#430] opened 2022-11-06 20:50 UTC
I tried to use juliaup on the OLCF HPC system "Summit". This fails:

```sh
$ curl -fsSL https://install.julialang.org | sh

info: downloading installer
curl: (22) The requested URL returned error: 404
juliaup: command failed: downloader https://julialang-s3.julialang.org/juliaup/bin/juliainstaller-1.7.24-powerpc64le-unknown-linux-gnu /tmp/tmp.QgYYKkrw9P/juliainstaller powerpc64le-unknown-linux-gnu
```

It seems that the url `https://julialang-s3.julialang.org/juliaup/bin/juliainstaller-1.7.24-powerpc64le-unknown-linux-gnu` does not exist, presumably because this CPU architecture is not supported.

Could you add support for it?

**Comment by fingolfin** [comment] 2024-01-05 12:14
Duplicate of #304 ?

**Closed** 2024-01-13 20:02 UTC
Labels: enhancement
