### ISSUE TITLE
Installer error on Linux - "cannot open /dev/?: No such file"

### ISSUE THREAD

**Issue by kescobo** [JuliaLang/juliaup#399] opened 2022-09-12 15:23 UTC
On pop!_OS (ubuntu) - 

```
❯ curl -fsSL https://install.julialang.org | sh

info: downloading installer
sh: 134: cannot open /dev/?: No such file
```

I thought it might be a permissions issue, so I tried `curl -fsSL https://install.julialang.org | sudo sh`, but this didn't work either. I changed the install directory to on in my home folder (instead of `/root`) and added it to my PATH, but then get:

```
❯ juliaup add release
Error: `add` command failed to load configuration data.

Caused by:
    Could not create lockfile: Permission denied (os error 13).
```

**Comment by kescobo** [comment] 2022-09-12 15:24
The later problem was solved with 

```
❯ sudo chown kevin:kevin -R ~/.julia/juliaup
```

**Comment by mgiugliano** [comment] 2022-10-02 08:24
I get the same error, trying to install juliaup on a Google Colab notebook.

I am certainly aware of [this](https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_Colab_Notebook_Template.ipynb) approach, but was inspired by the much more concise alternative involving [jill](https://github.com/johnnychen94/colab-julia-bootstrap/blob/master/julia.ipynb).


Of course I am inside a container and `/dev` does not exist. Despite I am `root`, the solution proposed above did not work.
I tried also (but failed - in my specific use-case):

```bash
!curl -fsSL https://install.julialang.org --output juliaup-init.sh
!sh juliaup-init.sh --yes
```

I immediately realised that line 95 of `juliaup-init.sh` needed to be uncommented. This launched the install but (surprisingly) prompted the user (from within a Jupyter notebook cell), and I could not figure out how to suppress even that kind of interactivity.

**Comment by davidanthoff** [comment] 2022-12-13 23:10
Do we just fix this by enabling a quiet install option? In which case this would essentially just be a duplicate of https://github.com/JuliaLang/juliaup/issues/218 (in terms of what we need to do, not in terms of a problem).

**Comment by M-PERSIC** [comment] 2023-02-06 22:30
@davidanthoff I had the same issue as I was running juliaup in a Podman instance. I believe the issue is (was?)  because of attempting to write to the /dev directory , which is not permissible in a non-root container.

I worked around it by running the installer in non-interactive mode
`curl -fsSL https://install.julialang.org | sh -s -- -y` which proceeded smoothly though one does lose the ability to customize the install.

It does seems like the issue has been resolved, though, as with the latest release juliaup installation proceeds normally (just ran in an Ubuntu Jammy instance, `podman run -it --rm ubuntu:jammy`). If @kescobo is no longer having the same problem I would consider this issue fixed.

**Comment by kescobo** [comment] 2023-02-06 22:55
I haven't had cause to check this again on my Ubuntu machine. I'm fine to close

**Comment by M-PERSIC** [comment] 2023-02-06 23:23
Just booted a Pop!_OS VM to be sure, runs well!

**Comment by davidanthoff** [comment] 2023-02-07 02:23
Agreed, I think we can close this, the quiet option is the way to go for this scenario. We can still add more command line args for the installer to customize the install, but I think that is already tracked by a different issue.

**Closed by davidanthoff** 2023-02-07 02:23 UTC
Labels: bug, help wanted
