### ISSUE TITLE
Enable transfer of default environment when updating julia

### ISSUE THREAD

**Issue by TorkelE** [JuliaLang/juliaup#638] opened 2023-05-10 13:49 UTC
Also see this discourse discussion: https://discourse.julialang.org/t/updated-julia-via-juliaup-packages-are-no-longer-avaiable/98612/3

In Julia, I have a default environment with a couple of packages. When I update julai using juliaup, these disappear. Would it be possible either by default or by using a flag, to have juliaup transfer this default environment to my new version?

**Comment by davidanthoff** [comment] 2023-05-10 18:01
Duplicate of https://github.com/JuliaLang/juliaup/issues/44.

**Closed by davidanthoff** 2023-05-10 18:01 UTC
