### ISSUE TITLE
Juliaup launcher Crash Report

### ISSUE THREAD

**Issue by ashwani-rathee** [JuliaLang/juliaup#727] opened 2023-09-06 14:36 UTC
name = "Juliaup launcher"
operating_system = "Windows 10.0.22621 (Windows 11 CoreSingleLanguage) [64-bit]"
crate_version = "1.11.22"
explanation = """
Panic occurred in file 'src/bin/julialauncher.rs' at line 369
"""
cause = "called `Result::unwrap()` on an `Err` value: TryFromIntError(())"
method = "Panic"
backtrace = """

   0: 0x7ff60f904b21 - <unresolved>
   1: 0x7ff60f8f23ef - <unresolved>
   2: 0x7ff60f8f24c6 - <unresolved>
   3: 0x7ff60f90a8b7 - <unresolved>
   4: 0x7ff60fa41c3c - <unresolved>
   5: 0x7ffb61b126ad - BaseThreadInitThunk
   6: 0x7ffb6302aa68 - RtlUserThreadStart"""

**Comment by davidanthoff** [comment] 2023-11-15 00:54
Duplicate of https://github.com/JuliaLang/juliaup/issues/709.

**Closed by davidanthoff** 2023-11-15 00:54 UTC
